version: "3"
services:
  pgdatabase:
    image: postgres:13
    networks:
      - dtc_ingest_network
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=ny_taxi
    ports:
      - 5432:5432
    volumes:
      - ./data/ny_taxi_postgres_data:/var/lib/postgresql/data:rw

  pgadmin:
    image: dpage/pgadmin4
    networks:
      - dtc_ingest_network
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 8080:80
networks:
  dtc_ingest_network: